
# This makefile is required in order to keep the cpplib project open
# in eclipse so that no errors will be signalled.  

all : 
	@echo Does nothing! 
	@echo If you want to build a library, you have to run the corresponding makefile from the library\'s folder.
	
	
clean :
	@echo clean