


expand: include/boost_1_45_0/make_dep_file
	

include/boost_1_45_0/make_dep_file: archives/boost_1_45_0.tar.bz2
	tar -xjf archives/boost_1_45_0.tar.bz2 -C include/
	touch include/boost_1_45_0/make_dep_file	

	

clean:
	rm -Rf include/boost_1_45_0/	