/*
* Copyright (C) 2013 Nivis LLC.
* Email:   opensource@nivis.com
* Website: http://www.nivis.com
*
* This program is free software: you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation, version 3 of the License.
* 
* Redistribution and use in source and binary forms must retain this
* copyright notice.

* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License
* along with this program.  If not, see <http://www.gnu.org/licenses/>.
*
*/


#include "Table.h"


namespace hart7 {
namespace gateway {


////////////////////////////////////////////1//////////////////////////////////////////////////
	 CREATE_CMD_RESP_BIN_LEN(C000_ReadUniqueIdentifier) 
	 CREATE_CMD_RESP_BIN_LEN(C001_ReadPrimaryVariable) 
	 CREATE_CMD_RESP_BIN_LEN(C002_ReadLoopCurrentAndPercentOfRange) 
	 CREATE_CMD_RESP_BIN_LEN(C003_ReadDynamicVariablesAndLoopCurrent) 
	 CREATE_CMD_RESP_BIN_LEN(C006_WritePollingAddress) 
	 CREATE_CMD_RESP_BIN_LEN(C007_ReadLoopConfiguration) 
	 CREATE_CMD_RESP_BIN_LEN(C008_ReadDynamicVariableClassifications) 
	 CREATE_CMD_RESP_BIN_LEN(C009_ReadDeviceVariablesWithStatus) 
	 CREATE_CMD_RESP_BIN_LEN(C011_ReadUniqueIdentifierAssociatedWithTag) 
	 CREATE_CMD_RESP_BIN_LEN(C012_ReadMessage) 
	 CREATE_CMD_RESP_BIN_LEN(C013_ReadTagDescriptorDate) 
	 CREATE_CMD_RESP_BIN_LEN(C014_ReadPrimaryVariableTransducerInformation) 
	 CREATE_CMD_RESP_BIN_LEN(C015_ReadDeviceInformation) 
	 CREATE_CMD_RESP_BIN_LEN(C016_ReadFinalAssemblyNumber) 
	 CREATE_CMD_RESP_BIN_LEN(C017_WriteMessage) 
	 CREATE_CMD_RESP_BIN_LEN(C018_WriteTagDescriptorDate) 
	 CREATE_CMD_RESP_BIN_LEN(C019_WriteFinalAssemblyNumber) 
	 CREATE_CMD_RESP_BIN_LEN(C020_ReadLongTag) 
	 CREATE_CMD_RESP_BIN_LEN(C021_ReadUniqueIdentifierAssociatedWithLongTag) 
	 CREATE_CMD_RESP_BIN_LEN(C022_WriteLongTag) 
	 CREATE_CMD_RESP_BIN_LEN(C033_ReadDeviceVariables) 
	 CREATE_CMD_RESP_BIN_LEN(C034_WritePrimaryVariableDampingValue) 
	 CREATE_CMD_RESP_BIN_LEN(C035_WritePrimaryVariableRangeValues) 
	 CREATE_CMD_RESP_BIN_LEN(C036_SetPrimaryVariableUpperRangeValue) 
	 CREATE_CMD_RESP_BIN_LEN(C037_SetPrimaryVariableLowerRangeValue) 
	 CREATE_CMD_RESP_BIN_LEN(C038_ResetConfigurationChangedFlag) 
	 CREATE_CMD_RESP_BIN_LEN(C040_EnterExitFixedCurrentMode) 
	 CREATE_CMD_RESP_BIN_LEN(C041_PerformSelfTest) 
	 CREATE_CMD_RESP_BIN_LEN(C042_PerformDeviceReset) 
	 CREATE_CMD_RESP_BIN_LEN(C043_SetPrimaryVariableZero) 
	 CREATE_CMD_RESP_BIN_LEN(C044_WritePrimaryVariableUnits) 
	 CREATE_CMD_RESP_BIN_LEN(C045_TrimLoopCurrentZero) 
	 CREATE_CMD_RESP_BIN_LEN(C046_TrimLoopCurrentGain) 
	 CREATE_CMD_RESP_BIN_LEN(C047_WritePrimaryVariableTransferFunction) 
	 CREATE_CMD_RESP_BIN_LEN(C048_ReadAdditionalDeviceStatus) 
	 CREATE_CMD_RESP_BIN_LEN(C049_WritePrimaryVariableTransducerSerialNumber) 
	 CREATE_CMD_RESP_BIN_LEN(C050_ReadDynamicVariableAssignments) 
	 CREATE_CMD_RESP_BIN_LEN(C051_WriteDynamicVariableAssignments) 
	 CREATE_CMD_RESP_BIN_LEN(C052_SetDeviceVariableZero) 
	 CREATE_CMD_RESP_BIN_LEN(C053_WriteDeviceVariableUnits) 
	 CREATE_CMD_RESP_BIN_LEN(C054_ReadDeviceVariableInformation) 
	 CREATE_CMD_RESP_BIN_LEN(C055_WriteDeviceVariableDampingValue) 
	 CREATE_CMD_RESP_BIN_LEN(C056_WriteDeviceVariableTransducerSerialNo) 
	 CREATE_CMD_RESP_BIN_LEN(C059_WriteNumberOfResponsePreambles) 
	 CREATE_CMD_RESP_BIN_LEN(C060_ReadAnalogChannelAndPercentOfRange) 
	 CREATE_CMD_RESP_BIN_LEN(C062_ReadAnalogChannels) 
	 CREATE_CMD_RESP_BIN_LEN(C063_ReadAnalogChannelInformation) 
	 CREATE_CMD_RESP_BIN_LEN(C064_WriteAnalogChannelAdditionalDampingValue) 
	 CREATE_CMD_RESP_BIN_LEN(C065_WriteAnalogChannelRangeValues) 
	 CREATE_CMD_RESP_BIN_LEN(C066_EnterExitFixedAnalogChannelMode) 
	 CREATE_CMD_RESP_BIN_LEN(C067_TrimAnalogChannelZero) 
	 CREATE_CMD_RESP_BIN_LEN(C068_TrimAnalogChannelGain) 
	 CREATE_CMD_RESP_BIN_LEN(C069_WriteAnalogChannelTransferFunction) 
	 CREATE_CMD_RESP_BIN_LEN(C070_ReadAnalogChannelEndpointValues) 
	 CREATE_CMD_RESP_BIN_LEN(C071_LockDevice) 
	 CREATE_CMD_RESP_BIN_LEN(C072_Squawk) 
	 CREATE_CMD_RESP_BIN_LEN(C073_FindDevice) 
	 CREATE_CMD_RESP_BIN_LEN(C074_ReadIOSystemCapabilities) 
	 CREATE_CMD_RESP_BIN_LEN(C075_PollSubDevice) 
	 CREATE_CMD_RESP_BIN_LEN(C076_ReadLockDeviceState) 
	 CREATE_CMD_RESP_BIN_LEN(C077_SendCommandToSubDevice) 
	 CREATE_CMD_RESP_BIN_LEN(C078_ReadAggregatedCommands) 
	 CREATE_CMD_RESP_BIN_LEN(C079_WriteDeviceVariable) 
	 CREATE_CMD_RESP_BIN_LEN(C080_ReadDeviceVariableTrimPoints) 
	 CREATE_CMD_RESP_BIN_LEN(C081_ReadDeviceVariableTrimGuidelines) 
	 CREATE_CMD_RESP_BIN_LEN(C082_WriteDeviceVariableTrimPoint) 
	 CREATE_CMD_RESP_BIN_LEN(C083_ResetDeviceVariableTrim) 
	 CREATE_CMD_RESP_BIN_LEN(C084_ReadSubDeviceIdentitySummary) 
	 CREATE_CMD_RESP_BIN_LEN(C085_ReadIOChannelStatistics) 
	 CREATE_CMD_RESP_BIN_LEN(C086_ReadSubDeviceStatistics) 
	 CREATE_CMD_RESP_BIN_LEN(C087_WriteIOSystemMasterMode) 
	 CREATE_CMD_RESP_BIN_LEN(C088_WriteIOSystemRetryCount) 
	 CREATE_CMD_RESP_BIN_LEN(C089_SetRealTimeClock) 
	 CREATE_CMD_RESP_BIN_LEN(C090_ReadRealTimeClock) 
	 CREATE_CMD_RESP_BIN_LEN(C091_ReadTrendConfiguration) 
	 CREATE_CMD_RESP_BIN_LEN(C092_WriteTrendConfiguration) 
	 CREATE_CMD_RESP_BIN_LEN(C093_ReadTrend) 
	 CREATE_CMD_RESP_BIN_LEN(C094_ReadIOSystemClientSideCommunicationStatistics) 
	 CREATE_CMD_RESP_BIN_LEN(C095_ReadDeviceCommunicationsStatistics) 
	 CREATE_CMD_RESP_BIN_LEN(C096_ReadSynchronousAction) 
	 CREATE_CMD_RESP_BIN_LEN(C097_ConfigureSynchronousAction) 
	 CREATE_CMD_RESP_BIN_LEN(C098_ReadCommandAction) 
	 CREATE_CMD_RESP_BIN_LEN(C099_ConfigureCommandAction) 
	 CREATE_CMD_RESP_BIN_LEN(C101_ReadSubDeviceToBurstMessageMap) 
	 CREATE_CMD_RESP_BIN_LEN(C102_MapSubDeviceToBurstMessage) 
	 CREATE_CMD_RESP_BIN_LEN(C103_WriteBurstPeriod) 
	 CREATE_CMD_RESP_BIN_LEN(C104_WriteBurstTrigger) 
	 CREATE_CMD_RESP_BIN_LEN(C105_ReadBurstModeConfiguration) 
	 CREATE_CMD_RESP_BIN_LEN(C106_FlushDelayedResponses) 
	 CREATE_CMD_RESP_BIN_LEN(C107_WriteBurstDeviceVariables) 
	 CREATE_CMD_RESP_BIN_LEN(C108_WriteBurstModeCommandNumber) 
	 CREATE_CMD_RESP_BIN_LEN(C109_BurstModeControl) 
	 CREATE_CMD_RESP_BIN_LEN(C113_CatchDeviceVariable) 
	 CREATE_CMD_RESP_BIN_LEN(C114_ReadCaughtDeviceVariable) 
	 CREATE_CMD_RESP_BIN_LEN(C115_ReadEventNotificationSummary) 
	 CREATE_CMD_RESP_BIN_LEN(C116_WriteEventNotificationBitMask) 
	 CREATE_CMD_RESP_BIN_LEN(C117_WriteEventNotificationTiming) 
	 CREATE_CMD_RESP_BIN_LEN(C118_EventNotificationControl) 
	 CREATE_CMD_RESP_BIN_LEN(C119_AcknowledgeEventNotification)
	 CREATE_CMD_RESP_BIN_LEN(C178_PublishedDynamicData)
	 CREATE_CMD_RESP_BIN_LEN(C512_ReadCountryCode) 
	//	 CREATE_CMD_RESP_BIN_LEN(C513_ReadCountryCode) 
	 CREATE_CMD_RESP_BIN_LEN(C768_WriteJoinKey) 
	 CREATE_CMD_RESP_BIN_LEN(C769_ReadJoinStatus) 
	 CREATE_CMD_RESP_BIN_LEN(C770_RequestActiveAdvertise) 
	 CREATE_CMD_RESP_BIN_LEN(C771_ForceJoin) 
	 CREATE_CMD_RESP_BIN_LEN(C772_ReadJoinModeConfiguration) 
	 CREATE_CMD_RESP_BIN_LEN(C773_WriteNetworkId) 
	 CREATE_CMD_RESP_BIN_LEN(C774_ReadNetworkId) 
	 CREATE_CMD_RESP_BIN_LEN(C777_ReadWirelessDeviceInformation) 
	 CREATE_CMD_RESP_BIN_LEN(C778_ReadBatteryLife) 
	 CREATE_CMD_RESP_BIN_LEN(C779_ReportDeviceHealth) 
	 CREATE_CMD_RESP_BIN_LEN(C780_ReportNeighborHealthList) 
	 CREATE_CMD_RESP_BIN_LEN(C781_ReadDeviceNicknameAddress) 
	 CREATE_CMD_RESP_BIN_LEN(C782_ReadSessionEntries) 
	 CREATE_CMD_RESP_BIN_LEN(C783_ReadSuperframeList) 
	 CREATE_CMD_RESP_BIN_LEN(C784_ReadLinkList) 
	 CREATE_CMD_RESP_BIN_LEN(C785_ReadGraphList) 
	 CREATE_CMD_RESP_BIN_LEN(C786_ReadNeighborPropertyFlag) 
	 CREATE_CMD_RESP_BIN_LEN(C787_ReportNeighborSignalLevels) 
	 CREATE_CMD_RESP_BIN_LEN(C788_AlarmPathDown) 
	 CREATE_CMD_RESP_BIN_LEN(C789_AlarmSourceRouteFailed) 
	 CREATE_CMD_RESP_BIN_LEN(C790_AlarmGraphRouteFailed) 
	 CREATE_CMD_RESP_BIN_LEN(C791_AlarmTransportLayerFailed) 
	 CREATE_CMD_RESP_BIN_LEN(C793_WriteUTCTime) 
	 CREATE_CMD_RESP_BIN_LEN(C794_ReadUTCTime) 
	 CREATE_CMD_RESP_BIN_LEN(C795_WriteTimerInterval) 
	 CREATE_CMD_RESP_BIN_LEN(C796_ReadTimerInterval) 
	 CREATE_CMD_RESP_BIN_LEN(C797_WriteRadioPower) 
	 CREATE_CMD_RESP_BIN_LEN(C798_ReadRadioPower) 
	 CREATE_CMD_RESP_BIN_LEN(C799_RequestService) 
	 CREATE_CMD_RESP_BIN_LEN(C800_ReadServiceList) 
	 CREATE_CMD_RESP_BIN_LEN(C801_DeleteService) 
	 CREATE_CMD_RESP_BIN_LEN(C802_ReadRouteList) 
	 CREATE_CMD_RESP_BIN_LEN(C803_ReadSourceRoute) 
	 CREATE_CMD_RESP_BIN_LEN(C804_ReadRadioCCAMode) 
	 CREATE_CMD_RESP_BIN_LEN(C805_WriteRadioCCAMode) 
	 CREATE_CMD_RESP_BIN_LEN(C806_ReadHandheldSuperframe) 
	 CREATE_CMD_RESP_BIN_LEN(C807_RequestHandheldSuperframeMode) 
	 CREATE_CMD_RESP_BIN_LEN(C808_ReadTimeToLive) 
	 CREATE_CMD_RESP_BIN_LEN(C809_WriteTimeToLive) 
	 CREATE_CMD_RESP_BIN_LEN(C810_ReadJoinPriority) 
	 CREATE_CMD_RESP_BIN_LEN(C811_WriteJoinPriority) 
	 CREATE_CMD_RESP_BIN_LEN(C812_ReadPacketReceivePriority) 
	 CREATE_CMD_RESP_BIN_LEN(C813_WritePacketReceivePriority) 
	 CREATE_CMD_RESP_BIN_LEN(C814_ReadDeviceListEntries) 
	 CREATE_CMD_RESP_BIN_LEN(C815_AddDeviceListTableEntry) 
	 CREATE_CMD_RESP_BIN_LEN(C816_DeleteDeviceListTableEntry) 
	 CREATE_CMD_RESP_BIN_LEN(C817_ReadChannelBlacklist) 
	 CREATE_CMD_RESP_BIN_LEN(C818_WriteChannelBlacklist) 
	 CREATE_CMD_RESP_BIN_LEN(C819_ReadBackOffExponent) 
	 CREATE_CMD_RESP_BIN_LEN(C820_WriteBackOffExponent) 
	 CREATE_CMD_RESP_BIN_LEN(C821_WriteNetworkAccessMode) 
	 CREATE_CMD_RESP_BIN_LEN(C822_ReadNetworkAccessMode) 
	 CREATE_CMD_RESP_BIN_LEN(C823_RequestSession) 
	 CREATE_CMD_RESP_BIN_LEN(C832_ReadNetworkDeviceIdentity) 
	 CREATE_CMD_RESP_BIN_LEN(C833_ReadNetworkDeviceNeighbourHealth) 
	 CREATE_CMD_RESP_BIN_LEN(C834_ReadNetworkTopologyInformation) 
	 CREATE_CMD_RESP_BIN_LEN(C835_ReadBurstMessageList) 
	 CREATE_CMD_RESP_BIN_LEN(C836_FlushCacheResponses) 
	 CREATE_CMD_RESP_BIN_LEN(C837_WriteUpdateNotificationBitMask) 
	 CREATE_CMD_RESP_BIN_LEN(C838_ReadUpdateNotificationBitMask) 
	 CREATE_CMD_RESP_BIN_LEN(C839_ChangeNotification) 
	 CREATE_CMD_RESP_BIN_LEN(C840_ReadDeviceStatistics) 
	 CREATE_CMD_RESP_BIN_LEN(C841_ReadNetworkDeviceIdentityByNickname) 
	 CREATE_CMD_RESP_BIN_LEN(C842_WriteDeviceSchedulingFlags) 
	 CREATE_CMD_RESP_BIN_LEN(C843_ReadDeviceSchedulingFlags) 
	 CREATE_CMD_RESP_BIN_LEN(C844_ReadNetworkConstraints) 
	 CREATE_CMD_RESP_BIN_LEN(C845_WriteNetworkConstraints) 
	 CREATE_CMD_RESP_BIN_LEN(C960_DisconnectDevice) 
	 CREATE_CMD_RESP_BIN_LEN(C961_WriteNetworkKey) 
	 CREATE_CMD_RESP_BIN_LEN(C962_WriteDeviceNicknameAddress) 
	 CREATE_CMD_RESP_BIN_LEN(C963_WriteSession) 
	 CREATE_CMD_RESP_BIN_LEN(C964_DeleteSession) 
	 CREATE_CMD_RESP_BIN_LEN(C965_WriteSuperframe) 
	 CREATE_CMD_RESP_BIN_LEN(C966_DeleteSuperframe) 
	 CREATE_CMD_RESP_BIN_LEN(C967_WriteLink) 
	 CREATE_CMD_RESP_BIN_LEN(C968_DeleteLink) 
	 CREATE_CMD_RESP_BIN_LEN(C969_WriteGraphNeighbourPair) 
	 CREATE_CMD_RESP_BIN_LEN(C970_DeleteGraphConnection) 
	 CREATE_CMD_RESP_BIN_LEN(C971_WriteNeighbourPropertyFlag) 
	 CREATE_CMD_RESP_BIN_LEN(C972_SuspendDevices) 
	 CREATE_CMD_RESP_BIN_LEN(C973_WriteService) 
	 CREATE_CMD_RESP_BIN_LEN(C974_WriteRoute) 
	 CREATE_CMD_RESP_BIN_LEN(C975_DeleteRoute) 
	 CREATE_CMD_RESP_BIN_LEN(C976_WriteSourceRoute) 
	 CREATE_CMD_RESP_BIN_LEN(C977_DeleteSourceRoute) 
/////////////////////////////////////////2/////////////////////////////////////////////////////
	CREATE_CMD_RESP_PARSED_LEN(C000_ReadUniqueIdentifier) 
	CREATE_CMD_RESP_PARSED_LEN(C001_ReadPrimaryVariable) 
	CREATE_CMD_RESP_PARSED_LEN(C002_ReadLoopCurrentAndPercentOfRange) 
	CREATE_CMD_RESP_PARSED_LEN(C003_ReadDynamicVariablesAndLoopCurrent) 
	CREATE_CMD_RESP_PARSED_LEN(C006_WritePollingAddress) 
	CREATE_CMD_RESP_PARSED_LEN(C007_ReadLoopConfiguration) 
	CREATE_CMD_RESP_PARSED_LEN(C008_ReadDynamicVariableClassifications) 
	CREATE_CMD_RESP_PARSED_LEN(C009_ReadDeviceVariablesWithStatus) 
	CREATE_CMD_RESP_PARSED_LEN(C011_ReadUniqueIdentifierAssociatedWithTag) 
	CREATE_CMD_RESP_PARSED_LEN(C012_ReadMessage) 
	CREATE_CMD_RESP_PARSED_LEN(C013_ReadTagDescriptorDate) 
	CREATE_CMD_RESP_PARSED_LEN(C014_ReadPrimaryVariableTransducerInformation) 
	CREATE_CMD_RESP_PARSED_LEN(C015_ReadDeviceInformation) 
	CREATE_CMD_RESP_PARSED_LEN(C016_ReadFinalAssemblyNumber) 
	CREATE_CMD_RESP_PARSED_LEN(C017_WriteMessage) 
	CREATE_CMD_RESP_PARSED_LEN(C018_WriteTagDescriptorDate) 
	CREATE_CMD_RESP_PARSED_LEN(C019_WriteFinalAssemblyNumber) 
	CREATE_CMD_RESP_PARSED_LEN(C020_ReadLongTag) 
	CREATE_CMD_RESP_PARSED_LEN(C021_ReadUniqueIdentifierAssociatedWithLongTag) 
	CREATE_CMD_RESP_PARSED_LEN(C022_WriteLongTag) 
	CREATE_CMD_RESP_PARSED_LEN(C033_ReadDeviceVariables) 
	CREATE_CMD_RESP_PARSED_LEN(C034_WritePrimaryVariableDampingValue) 
	CREATE_CMD_RESP_PARSED_LEN(C035_WritePrimaryVariableRangeValues) 
	CREATE_CMD_RESP_PARSED_LEN(C036_SetPrimaryVariableUpperRangeValue) 
	CREATE_CMD_RESP_PARSED_LEN(C037_SetPrimaryVariableLowerRangeValue) 
	CREATE_CMD_RESP_PARSED_LEN(C038_ResetConfigurationChangedFlag) 
	CREATE_CMD_RESP_PARSED_LEN(C040_EnterExitFixedCurrentMode) 
	CREATE_CMD_RESP_PARSED_LEN(C041_PerformSelfTest) 
	CREATE_CMD_RESP_PARSED_LEN(C042_PerformDeviceReset) 
	CREATE_CMD_RESP_PARSED_LEN(C043_SetPrimaryVariableZero) 
	CREATE_CMD_RESP_PARSED_LEN(C044_WritePrimaryVariableUnits) 
	CREATE_CMD_RESP_PARSED_LEN(C045_TrimLoopCurrentZero) 
	CREATE_CMD_RESP_PARSED_LEN(C046_TrimLoopCurrentGain) 
	CREATE_CMD_RESP_PARSED_LEN(C047_WritePrimaryVariableTransferFunction) 
	CREATE_CMD_RESP_PARSED_LEN(C048_ReadAdditionalDeviceStatus) 
	CREATE_CMD_RESP_PARSED_LEN(C049_WritePrimaryVariableTransducerSerialNumber) 
	CREATE_CMD_RESP_PARSED_LEN(C050_ReadDynamicVariableAssignments) 
	CREATE_CMD_RESP_PARSED_LEN(C051_WriteDynamicVariableAssignments) 
	CREATE_CMD_RESP_PARSED_LEN(C052_SetDeviceVariableZero) 
	CREATE_CMD_RESP_PARSED_LEN(C053_WriteDeviceVariableUnits) 
	CREATE_CMD_RESP_PARSED_LEN(C054_ReadDeviceVariableInformation) 
	CREATE_CMD_RESP_PARSED_LEN(C055_WriteDeviceVariableDampingValue) 
	CREATE_CMD_RESP_PARSED_LEN(C056_WriteDeviceVariableTransducerSerialNo) 
	CREATE_CMD_RESP_PARSED_LEN(C059_WriteNumberOfResponsePreambles) 
	CREATE_CMD_RESP_PARSED_LEN(C060_ReadAnalogChannelAndPercentOfRange) 
	CREATE_CMD_RESP_PARSED_LEN(C062_ReadAnalogChannels) 
	CREATE_CMD_RESP_PARSED_LEN(C063_ReadAnalogChannelInformation) 
	CREATE_CMD_RESP_PARSED_LEN(C064_WriteAnalogChannelAdditionalDampingValue) 
	CREATE_CMD_RESP_PARSED_LEN(C065_WriteAnalogChannelRangeValues) 
	CREATE_CMD_RESP_PARSED_LEN(C066_EnterExitFixedAnalogChannelMode) 
	CREATE_CMD_RESP_PARSED_LEN(C067_TrimAnalogChannelZero) 
	CREATE_CMD_RESP_PARSED_LEN(C068_TrimAnalogChannelGain) 
	CREATE_CMD_RESP_PARSED_LEN(C069_WriteAnalogChannelTransferFunction) 
	CREATE_CMD_RESP_PARSED_LEN(C070_ReadAnalogChannelEndpointValues) 
	CREATE_CMD_RESP_PARSED_LEN(C071_LockDevice) 
	CREATE_CMD_RESP_PARSED_LEN(C072_Squawk) 
	CREATE_CMD_RESP_PARSED_LEN(C073_FindDevice) 
	CREATE_CMD_RESP_PARSED_LEN(C074_ReadIOSystemCapabilities) 
	CREATE_CMD_RESP_PARSED_LEN(C075_PollSubDevice) 
	CREATE_CMD_RESP_PARSED_LEN(C076_ReadLockDeviceState) 
	CREATE_CMD_RESP_PARSED_LEN(C077_SendCommandToSubDevice) 
	CREATE_CMD_RESP_PARSED_LEN(C078_ReadAggregatedCommands) 
	CREATE_CMD_RESP_PARSED_LEN(C079_WriteDeviceVariable) 
	CREATE_CMD_RESP_PARSED_LEN(C080_ReadDeviceVariableTrimPoints) 
	CREATE_CMD_RESP_PARSED_LEN(C081_ReadDeviceVariableTrimGuidelines) 
	CREATE_CMD_RESP_PARSED_LEN(C082_WriteDeviceVariableTrimPoint) 
	CREATE_CMD_RESP_PARSED_LEN(C083_ResetDeviceVariableTrim) 
	CREATE_CMD_RESP_PARSED_LEN(C084_ReadSubDeviceIdentitySummary) 
	CREATE_CMD_RESP_PARSED_LEN(C085_ReadIOChannelStatistics) 
	CREATE_CMD_RESP_PARSED_LEN(C086_ReadSubDeviceStatistics) 
	CREATE_CMD_RESP_PARSED_LEN(C087_WriteIOSystemMasterMode) 
	CREATE_CMD_RESP_PARSED_LEN(C088_WriteIOSystemRetryCount) 
	CREATE_CMD_RESP_PARSED_LEN(C089_SetRealTimeClock) 
	CREATE_CMD_RESP_PARSED_LEN(C090_ReadRealTimeClock) 
	CREATE_CMD_RESP_PARSED_LEN(C091_ReadTrendConfiguration) 
	CREATE_CMD_RESP_PARSED_LEN(C092_WriteTrendConfiguration) 
	CREATE_CMD_RESP_PARSED_LEN(C093_ReadTrend) 
	CREATE_CMD_RESP_PARSED_LEN(C094_ReadIOSystemClientSideCommunicationStatistics) 
	CREATE_CMD_RESP_PARSED_LEN(C095_ReadDeviceCommunicationsStatistics) 
	CREATE_CMD_RESP_PARSED_LEN(C096_ReadSynchronousAction) 
	CREATE_CMD_RESP_PARSED_LEN(C097_ConfigureSynchronousAction) 
	CREATE_CMD_RESP_PARSED_LEN(C098_ReadCommandAction) 
	CREATE_CMD_RESP_PARSED_LEN(C099_ConfigureCommandAction) 
	CREATE_CMD_RESP_PARSED_LEN(C101_ReadSubDeviceToBurstMessageMap) 
	CREATE_CMD_RESP_PARSED_LEN(C102_MapSubDeviceToBurstMessage) 
	CREATE_CMD_RESP_PARSED_LEN(C103_WriteBurstPeriod) 
	CREATE_CMD_RESP_PARSED_LEN(C104_WriteBurstTrigger) 
	CREATE_CMD_RESP_PARSED_LEN(C105_ReadBurstModeConfiguration) 
	CREATE_CMD_RESP_PARSED_LEN(C106_FlushDelayedResponses) 
	CREATE_CMD_RESP_PARSED_LEN(C107_WriteBurstDeviceVariables) 
	CREATE_CMD_RESP_PARSED_LEN(C108_WriteBurstModeCommandNumber) 
	CREATE_CMD_RESP_PARSED_LEN(C109_BurstModeControl) 
	CREATE_CMD_RESP_PARSED_LEN(C113_CatchDeviceVariable) 
	CREATE_CMD_RESP_PARSED_LEN(C114_ReadCaughtDeviceVariable) 
	CREATE_CMD_RESP_PARSED_LEN(C115_ReadEventNotificationSummary) 
	CREATE_CMD_RESP_PARSED_LEN(C116_WriteEventNotificationBitMask) 
	CREATE_CMD_RESP_PARSED_LEN(C117_WriteEventNotificationTiming) 
	CREATE_CMD_RESP_PARSED_LEN(C118_EventNotificationControl) 
	CREATE_CMD_RESP_PARSED_LEN(C119_AcknowledgeEventNotification)
	CREATE_CMD_RESP_PARSED_LEN(C178_PublishedDynamicData)
	CREATE_CMD_RESP_PARSED_LEN(C512_ReadCountryCode) 
	//	CREATE_CMD_RESP_PARSED_LEN(C513_ReadCountryCode) 
	CREATE_CMD_RESP_PARSED_LEN(C768_WriteJoinKey) 
	CREATE_CMD_RESP_PARSED_LEN(C769_ReadJoinStatus) 
	CREATE_CMD_RESP_PARSED_LEN(C770_RequestActiveAdvertise) 
	CREATE_CMD_RESP_PARSED_LEN(C771_ForceJoin) 
	CREATE_CMD_RESP_PARSED_LEN(C772_ReadJoinModeConfiguration) 
	CREATE_CMD_RESP_PARSED_LEN(C773_WriteNetworkId) 
	CREATE_CMD_RESP_PARSED_LEN(C774_ReadNetworkId) 
	CREATE_CMD_RESP_PARSED_LEN(C777_ReadWirelessDeviceInformation) 
	CREATE_CMD_RESP_PARSED_LEN(C778_ReadBatteryLife) 
	CREATE_CMD_RESP_PARSED_LEN(C779_ReportDeviceHealth) 
	CREATE_CMD_RESP_PARSED_LEN(C780_ReportNeighborHealthList) 
	CREATE_CMD_RESP_PARSED_LEN(C781_ReadDeviceNicknameAddress) 
	CREATE_CMD_RESP_PARSED_LEN(C782_ReadSessionEntries) 
	CREATE_CMD_RESP_PARSED_LEN(C783_ReadSuperframeList) 
	CREATE_CMD_RESP_PARSED_LEN(C784_ReadLinkList) 
	CREATE_CMD_RESP_PARSED_LEN(C785_ReadGraphList) 
	CREATE_CMD_RESP_PARSED_LEN(C786_ReadNeighborPropertyFlag) 
	CREATE_CMD_RESP_PARSED_LEN(C787_ReportNeighborSignalLevels) 
	CREATE_CMD_RESP_PARSED_LEN(C788_AlarmPathDown) 
	CREATE_CMD_RESP_PARSED_LEN(C789_AlarmSourceRouteFailed) 
	CREATE_CMD_RESP_PARSED_LEN(C790_AlarmGraphRouteFailed) 
	CREATE_CMD_RESP_PARSED_LEN(C791_AlarmTransportLayerFailed) 
	CREATE_CMD_RESP_PARSED_LEN(C793_WriteUTCTime) 
	CREATE_CMD_RESP_PARSED_LEN(C794_ReadUTCTime) 
	CREATE_CMD_RESP_PARSED_LEN(C795_WriteTimerInterval) 
	CREATE_CMD_RESP_PARSED_LEN(C796_ReadTimerInterval) 
	CREATE_CMD_RESP_PARSED_LEN(C797_WriteRadioPower) 
	CREATE_CMD_RESP_PARSED_LEN(C798_ReadRadioPower) 
	CREATE_CMD_RESP_PARSED_LEN(C799_RequestService) 
	CREATE_CMD_RESP_PARSED_LEN(C800_ReadServiceList) 
	CREATE_CMD_RESP_PARSED_LEN(C801_DeleteService) 
	CREATE_CMD_RESP_PARSED_LEN(C802_ReadRouteList) 
	CREATE_CMD_RESP_PARSED_LEN(C803_ReadSourceRoute) 
	CREATE_CMD_RESP_PARSED_LEN(C804_ReadRadioCCAMode) 
	CREATE_CMD_RESP_PARSED_LEN(C805_WriteRadioCCAMode) 
	CREATE_CMD_RESP_PARSED_LEN(C806_ReadHandheldSuperframe) 
	CREATE_CMD_RESP_PARSED_LEN(C807_RequestHandheldSuperframeMode) 
	CREATE_CMD_RESP_PARSED_LEN(C808_ReadTimeToLive) 
	CREATE_CMD_RESP_PARSED_LEN(C809_WriteTimeToLive) 
	CREATE_CMD_RESP_PARSED_LEN(C810_ReadJoinPriority) 
	CREATE_CMD_RESP_PARSED_LEN(C811_WriteJoinPriority) 
	CREATE_CMD_RESP_PARSED_LEN(C812_ReadPacketReceivePriority) 
	CREATE_CMD_RESP_PARSED_LEN(C813_WritePacketReceivePriority) 
	CREATE_CMD_RESP_PARSED_LEN(C814_ReadDeviceListEntries) 
	CREATE_CMD_RESP_PARSED_LEN(C815_AddDeviceListTableEntry) 
	CREATE_CMD_RESP_PARSED_LEN(C816_DeleteDeviceListTableEntry) 
	CREATE_CMD_RESP_PARSED_LEN(C817_ReadChannelBlacklist) 
	CREATE_CMD_RESP_PARSED_LEN(C818_WriteChannelBlacklist) 
	CREATE_CMD_RESP_PARSED_LEN(C819_ReadBackOffExponent) 
	CREATE_CMD_RESP_PARSED_LEN(C820_WriteBackOffExponent) 
	CREATE_CMD_RESP_PARSED_LEN(C821_WriteNetworkAccessMode) 
	CREATE_CMD_RESP_PARSED_LEN(C822_ReadNetworkAccessMode) 
	CREATE_CMD_RESP_PARSED_LEN(C823_RequestSession) 
	CREATE_CMD_RESP_PARSED_LEN(C832_ReadNetworkDeviceIdentity) 
	CREATE_CMD_RESP_PARSED_LEN(C833_ReadNetworkDeviceNeighbourHealth) 
	CREATE_CMD_RESP_PARSED_LEN(C834_ReadNetworkTopologyInformation) 
	CREATE_CMD_RESP_PARSED_LEN(C835_ReadBurstMessageList) 
	CREATE_CMD_RESP_PARSED_LEN(C836_FlushCacheResponses) 
	CREATE_CMD_RESP_PARSED_LEN(C837_WriteUpdateNotificationBitMask) 
	CREATE_CMD_RESP_PARSED_LEN(C838_ReadUpdateNotificationBitMask) 
	CREATE_CMD_RESP_PARSED_LEN(C839_ChangeNotification) 
	CREATE_CMD_RESP_PARSED_LEN(C840_ReadDeviceStatistics) 
	CREATE_CMD_RESP_PARSED_LEN(C841_ReadNetworkDeviceIdentityByNickname) 
	CREATE_CMD_RESP_PARSED_LEN(C842_WriteDeviceSchedulingFlags) 
	CREATE_CMD_RESP_PARSED_LEN(C843_ReadDeviceSchedulingFlags) 
	CREATE_CMD_RESP_PARSED_LEN(C844_ReadNetworkConstraints) 
	CREATE_CMD_RESP_PARSED_LEN(C845_WriteNetworkConstraints) 
	CREATE_CMD_RESP_PARSED_LEN(C960_DisconnectDevice) 
	CREATE_CMD_RESP_PARSED_LEN(C961_WriteNetworkKey) 
	CREATE_CMD_RESP_PARSED_LEN(C962_WriteDeviceNicknameAddress) 
	CREATE_CMD_RESP_PARSED_LEN(C963_WriteSession) 
	CREATE_CMD_RESP_PARSED_LEN(C964_DeleteSession) 
	CREATE_CMD_RESP_PARSED_LEN(C965_WriteSuperframe) 
	CREATE_CMD_RESP_PARSED_LEN(C966_DeleteSuperframe) 
	CREATE_CMD_RESP_PARSED_LEN(C967_WriteLink) 
	CREATE_CMD_RESP_PARSED_LEN(C968_DeleteLink) 
	CREATE_CMD_RESP_PARSED_LEN(C969_WriteGraphNeighbourPair) 
	CREATE_CMD_RESP_PARSED_LEN(C970_DeleteGraphConnection) 
	CREATE_CMD_RESP_PARSED_LEN(C971_WriteNeighbourPropertyFlag) 
	CREATE_CMD_RESP_PARSED_LEN(C972_SuspendDevices) 
	CREATE_CMD_RESP_PARSED_LEN(C973_WriteService) 
	CREATE_CMD_RESP_PARSED_LEN(C974_WriteRoute) 
	CREATE_CMD_RESP_PARSED_LEN(C975_DeleteRoute) 
	CREATE_CMD_RESP_PARSED_LEN(C976_WriteSourceRoute) 
	CREATE_CMD_RESP_PARSED_LEN(C977_DeleteSourceRoute) 


/////////////////////////////////////////3/////////////////////////////////////////////////////
	CREATE_CMD_REQ_BIN_LEN(C000_ReadUniqueIdentifier) 
	CREATE_CMD_REQ_BIN_LEN(C001_ReadPrimaryVariable) 
	CREATE_CMD_REQ_BIN_LEN(C002_ReadLoopCurrentAndPercentOfRange) 
	CREATE_CMD_REQ_BIN_LEN(C003_ReadDynamicVariablesAndLoopCurrent) 
	CREATE_CMD_REQ_BIN_LEN(C006_WritePollingAddress) 
	CREATE_CMD_REQ_BIN_LEN(C007_ReadLoopConfiguration) 
	CREATE_CMD_REQ_BIN_LEN(C008_ReadDynamicVariableClassifications) 
	CREATE_CMD_REQ_BIN_LEN(C009_ReadDeviceVariablesWithStatus) 
	CREATE_CMD_REQ_BIN_LEN(C011_ReadUniqueIdentifierAssociatedWithTag) 
	CREATE_CMD_REQ_BIN_LEN(C012_ReadMessage) 
	CREATE_CMD_REQ_BIN_LEN(C013_ReadTagDescriptorDate) 
	CREATE_CMD_REQ_BIN_LEN(C014_ReadPrimaryVariableTransducerInformation) 
	CREATE_CMD_REQ_BIN_LEN(C015_ReadDeviceInformation) 
	CREATE_CMD_REQ_BIN_LEN(C016_ReadFinalAssemblyNumber) 
	CREATE_CMD_REQ_BIN_LEN(C017_WriteMessage) 
	CREATE_CMD_REQ_BIN_LEN(C018_WriteTagDescriptorDate) 
	CREATE_CMD_REQ_BIN_LEN(C019_WriteFinalAssemblyNumber) 
	CREATE_CMD_REQ_BIN_LEN(C020_ReadLongTag) 
	CREATE_CMD_REQ_BIN_LEN(C021_ReadUniqueIdentifierAssociatedWithLongTag) 
	CREATE_CMD_REQ_BIN_LEN(C022_WriteLongTag) 
	CREATE_CMD_REQ_BIN_LEN(C033_ReadDeviceVariables) 
	CREATE_CMD_REQ_BIN_LEN(C034_WritePrimaryVariableDampingValue) 
	CREATE_CMD_REQ_BIN_LEN(C035_WritePrimaryVariableRangeValues) 
	CREATE_CMD_REQ_BIN_LEN(C036_SetPrimaryVariableUpperRangeValue) 
	CREATE_CMD_REQ_BIN_LEN(C037_SetPrimaryVariableLowerRangeValue) 
	CREATE_CMD_REQ_BIN_LEN(C038_ResetConfigurationChangedFlag) 
	CREATE_CMD_REQ_BIN_LEN(C040_EnterExitFixedCurrentMode) 
	CREATE_CMD_REQ_BIN_LEN(C041_PerformSelfTest) 
	CREATE_CMD_REQ_BIN_LEN(C042_PerformDeviceReset) 
	CREATE_CMD_REQ_BIN_LEN(C043_SetPrimaryVariableZero) 
	CREATE_CMD_REQ_BIN_LEN(C044_WritePrimaryVariableUnits) 
	CREATE_CMD_REQ_BIN_LEN(C045_TrimLoopCurrentZero) 
	CREATE_CMD_REQ_BIN_LEN(C046_TrimLoopCurrentGain) 
	CREATE_CMD_REQ_BIN_LEN(C047_WritePrimaryVariableTransferFunction) 
	CREATE_CMD_REQ_BIN_LEN(C048_ReadAdditionalDeviceStatus) 
	CREATE_CMD_REQ_BIN_LEN(C049_WritePrimaryVariableTransducerSerialNumber) 
	CREATE_CMD_REQ_BIN_LEN(C050_ReadDynamicVariableAssignments) 
	CREATE_CMD_REQ_BIN_LEN(C051_WriteDynamicVariableAssignments) 
	CREATE_CMD_REQ_BIN_LEN(C052_SetDeviceVariableZero) 
	CREATE_CMD_REQ_BIN_LEN(C053_WriteDeviceVariableUnits) 
	CREATE_CMD_REQ_BIN_LEN(C054_ReadDeviceVariableInformation) 
	CREATE_CMD_REQ_BIN_LEN(C055_WriteDeviceVariableDampingValue) 
	CREATE_CMD_REQ_BIN_LEN(C056_WriteDeviceVariableTransducerSerialNo) 
	CREATE_CMD_REQ_BIN_LEN(C059_WriteNumberOfResponsePreambles) 
	CREATE_CMD_REQ_BIN_LEN(C060_ReadAnalogChannelAndPercentOfRange) 
	CREATE_CMD_REQ_BIN_LEN(C062_ReadAnalogChannels) 
	CREATE_CMD_REQ_BIN_LEN(C063_ReadAnalogChannelInformation) 
	CREATE_CMD_REQ_BIN_LEN(C064_WriteAnalogChannelAdditionalDampingValue) 
	CREATE_CMD_REQ_BIN_LEN(C065_WriteAnalogChannelRangeValues) 
	CREATE_CMD_REQ_BIN_LEN(C066_EnterExitFixedAnalogChannelMode) 
	CREATE_CMD_REQ_BIN_LEN(C067_TrimAnalogChannelZero) 
	CREATE_CMD_REQ_BIN_LEN(C068_TrimAnalogChannelGain) 
	CREATE_CMD_REQ_BIN_LEN(C069_WriteAnalogChannelTransferFunction) 
	CREATE_CMD_REQ_BIN_LEN(C070_ReadAnalogChannelEndpointValues) 
	CREATE_CMD_REQ_BIN_LEN(C071_LockDevice) 
	CREATE_CMD_REQ_BIN_LEN(C072_Squawk) 
	CREATE_CMD_REQ_BIN_LEN(C073_FindDevice) 
	CREATE_CMD_REQ_BIN_LEN(C074_ReadIOSystemCapabilities) 
	CREATE_CMD_REQ_BIN_LEN(C075_PollSubDevice) 
	CREATE_CMD_REQ_BIN_LEN(C076_ReadLockDeviceState) 
	CREATE_CMD_REQ_BIN_LEN(C077_SendCommandToSubDevice) 
	CREATE_CMD_REQ_BIN_LEN(C078_ReadAggregatedCommands) 
	CREATE_CMD_REQ_BIN_LEN(C079_WriteDeviceVariable) 
	CREATE_CMD_REQ_BIN_LEN(C080_ReadDeviceVariableTrimPoints) 
	CREATE_CMD_REQ_BIN_LEN(C081_ReadDeviceVariableTrimGuidelines) 
	CREATE_CMD_REQ_BIN_LEN(C082_WriteDeviceVariableTrimPoint) 
	CREATE_CMD_REQ_BIN_LEN(C083_ResetDeviceVariableTrim) 
	CREATE_CMD_REQ_BIN_LEN(C084_ReadSubDeviceIdentitySummary) 
	CREATE_CMD_REQ_BIN_LEN(C085_ReadIOChannelStatistics) 
	CREATE_CMD_REQ_BIN_LEN(C086_ReadSubDeviceStatistics) 
	CREATE_CMD_REQ_BIN_LEN(C087_WriteIOSystemMasterMode) 
	CREATE_CMD_REQ_BIN_LEN(C088_WriteIOSystemRetryCount) 
	CREATE_CMD_REQ_BIN_LEN(C089_SetRealTimeClock) 
	CREATE_CMD_REQ_BIN_LEN(C090_ReadRealTimeClock) 
	CREATE_CMD_REQ_BIN_LEN(C091_ReadTrendConfiguration) 
	CREATE_CMD_REQ_BIN_LEN(C092_WriteTrendConfiguration) 
	CREATE_CMD_REQ_BIN_LEN(C093_ReadTrend) 
	CREATE_CMD_REQ_BIN_LEN(C094_ReadIOSystemClientSideCommunicationStatistics) 
	CREATE_CMD_REQ_BIN_LEN(C095_ReadDeviceCommunicationsStatistics) 
	CREATE_CMD_REQ_BIN_LEN(C096_ReadSynchronousAction) 
	CREATE_CMD_REQ_BIN_LEN(C097_ConfigureSynchronousAction) 
	CREATE_CMD_REQ_BIN_LEN(C098_ReadCommandAction) 
	CREATE_CMD_REQ_BIN_LEN(C099_ConfigureCommandAction) 
	CREATE_CMD_REQ_BIN_LEN(C101_ReadSubDeviceToBurstMessageMap) 
	CREATE_CMD_REQ_BIN_LEN(C102_MapSubDeviceToBurstMessage) 
	CREATE_CMD_REQ_BIN_LEN(C103_WriteBurstPeriod) 
	CREATE_CMD_REQ_BIN_LEN(C104_WriteBurstTrigger) 
	CREATE_CMD_REQ_BIN_LEN(C105_ReadBurstModeConfiguration) 
	CREATE_CMD_REQ_BIN_LEN(C106_FlushDelayedResponses) 
	CREATE_CMD_REQ_BIN_LEN(C107_WriteBurstDeviceVariables) 
	CREATE_CMD_REQ_BIN_LEN(C108_WriteBurstModeCommandNumber) 
	CREATE_CMD_REQ_BIN_LEN(C109_BurstModeControl) 
	CREATE_CMD_REQ_BIN_LEN(C113_CatchDeviceVariable) 
	CREATE_CMD_REQ_BIN_LEN(C114_ReadCaughtDeviceVariable) 
	CREATE_CMD_REQ_BIN_LEN(C115_ReadEventNotificationSummary) 
	CREATE_CMD_REQ_BIN_LEN(C116_WriteEventNotificationBitMask) 
	CREATE_CMD_REQ_BIN_LEN(C117_WriteEventNotificationTiming) 
	CREATE_CMD_REQ_BIN_LEN(C118_EventNotificationControl) 
	CREATE_CMD_REQ_BIN_LEN(C119_AcknowledgeEventNotification) 
	CREATE_CMD_REQ_BIN_LEN(C178_PublishedDynamicData)
	CREATE_CMD_REQ_BIN_LEN(C512_ReadCountryCode) 
		//CREATE_CMD_REQ_BIN_LEN(C513_ReadCountryCode) 
	CREATE_CMD_REQ_BIN_LEN(C768_WriteJoinKey) 
	CREATE_CMD_REQ_BIN_LEN(C769_ReadJoinStatus) 
	CREATE_CMD_REQ_BIN_LEN(C770_RequestActiveAdvertise) 
	CREATE_CMD_REQ_BIN_LEN(C771_ForceJoin) 
	CREATE_CMD_REQ_BIN_LEN(C772_ReadJoinModeConfiguration) 
	CREATE_CMD_REQ_BIN_LEN(C773_WriteNetworkId) 
	CREATE_CMD_REQ_BIN_LEN(C774_ReadNetworkId) 
	CREATE_CMD_REQ_BIN_LEN(C777_ReadWirelessDeviceInformation) 
	CREATE_CMD_REQ_BIN_LEN(C778_ReadBatteryLife) 
	CREATE_CMD_REQ_BIN_LEN(C779_ReportDeviceHealth) 
	CREATE_CMD_REQ_BIN_LEN(C780_ReportNeighborHealthList) 
	CREATE_CMD_REQ_BIN_LEN(C781_ReadDeviceNicknameAddress) 
	CREATE_CMD_REQ_BIN_LEN(C782_ReadSessionEntries) 
	CREATE_CMD_REQ_BIN_LEN(C783_ReadSuperframeList) 
	CREATE_CMD_REQ_BIN_LEN(C784_ReadLinkList) 
	CREATE_CMD_REQ_BIN_LEN(C785_ReadGraphList) 
	CREATE_CMD_REQ_BIN_LEN(C786_ReadNeighborPropertyFlag) 
	CREATE_CMD_REQ_BIN_LEN(C787_ReportNeighborSignalLevels) 
	CREATE_CMD_REQ_BIN_LEN(C788_AlarmPathDown) 
	CREATE_CMD_REQ_BIN_LEN(C789_AlarmSourceRouteFailed) 
	CREATE_CMD_REQ_BIN_LEN(C790_AlarmGraphRouteFailed) 
	CREATE_CMD_REQ_BIN_LEN(C791_AlarmTransportLayerFailed) 
	CREATE_CMD_REQ_BIN_LEN(C793_WriteUTCTime) 
	CREATE_CMD_REQ_BIN_LEN(C794_ReadUTCTime) 
	CREATE_CMD_REQ_BIN_LEN(C795_WriteTimerInterval) 
	CREATE_CMD_REQ_BIN_LEN(C796_ReadTimerInterval) 
	CREATE_CMD_REQ_BIN_LEN(C797_WriteRadioPower) 
	CREATE_CMD_REQ_BIN_LEN(C798_ReadRadioPower) 
	CREATE_CMD_REQ_BIN_LEN(C799_RequestService) 
	CREATE_CMD_REQ_BIN_LEN(C800_ReadServiceList) 
	CREATE_CMD_REQ_BIN_LEN(C801_DeleteService) 
	CREATE_CMD_REQ_BIN_LEN(C802_ReadRouteList) 
	CREATE_CMD_REQ_BIN_LEN(C803_ReadSourceRoute) 
	CREATE_CMD_REQ_BIN_LEN(C804_ReadRadioCCAMode) 
	CREATE_CMD_REQ_BIN_LEN(C805_WriteRadioCCAMode) 
	CREATE_CMD_REQ_BIN_LEN(C806_ReadHandheldSuperframe) 
	CREATE_CMD_REQ_BIN_LEN(C807_RequestHandheldSuperframeMode) 
	CREATE_CMD_REQ_BIN_LEN(C808_ReadTimeToLive) 
	CREATE_CMD_REQ_BIN_LEN(C809_WriteTimeToLive) 
	CREATE_CMD_REQ_BIN_LEN(C810_ReadJoinPriority) 
	CREATE_CMD_REQ_BIN_LEN(C811_WriteJoinPriority) 
	CREATE_CMD_REQ_BIN_LEN(C812_ReadPacketReceivePriority) 
	CREATE_CMD_REQ_BIN_LEN(C813_WritePacketReceivePriority) 
	CREATE_CMD_REQ_BIN_LEN(C814_ReadDeviceListEntries) 
	CREATE_CMD_REQ_BIN_LEN(C815_AddDeviceListTableEntry) 
	CREATE_CMD_REQ_BIN_LEN(C816_DeleteDeviceListTableEntry) 
	CREATE_CMD_REQ_BIN_LEN(C817_ReadChannelBlacklist) 
	CREATE_CMD_REQ_BIN_LEN(C818_WriteChannelBlacklist) 
	CREATE_CMD_REQ_BIN_LEN(C819_ReadBackOffExponent) 
	CREATE_CMD_REQ_BIN_LEN(C820_WriteBackOffExponent) 
	CREATE_CMD_REQ_BIN_LEN(C821_WriteNetworkAccessMode) 
	CREATE_CMD_REQ_BIN_LEN(C822_ReadNetworkAccessMode) 
	CREATE_CMD_REQ_BIN_LEN(C823_RequestSession) 
	CREATE_CMD_REQ_BIN_LEN(C832_ReadNetworkDeviceIdentity) 
	CREATE_CMD_REQ_BIN_LEN(C833_ReadNetworkDeviceNeighbourHealth) 
	CREATE_CMD_REQ_BIN_LEN(C834_ReadNetworkTopologyInformation) 
	CREATE_CMD_REQ_BIN_LEN(C835_ReadBurstMessageList) 
	CREATE_CMD_REQ_BIN_LEN(C836_FlushCacheResponses) 
	CREATE_CMD_REQ_BIN_LEN(C837_WriteUpdateNotificationBitMask) 
	CREATE_CMD_REQ_BIN_LEN(C838_ReadUpdateNotificationBitMask) 
	CREATE_CMD_REQ_BIN_LEN(C839_ChangeNotification) 
	CREATE_CMD_REQ_BIN_LEN(C840_ReadDeviceStatistics) 
	CREATE_CMD_REQ_BIN_LEN(C841_ReadNetworkDeviceIdentityByNickname) 
	CREATE_CMD_REQ_BIN_LEN(C842_WriteDeviceSchedulingFlags) 
	CREATE_CMD_REQ_BIN_LEN(C843_ReadDeviceSchedulingFlags) 
	CREATE_CMD_REQ_BIN_LEN(C844_ReadNetworkConstraints) 
	CREATE_CMD_REQ_BIN_LEN(C845_WriteNetworkConstraints) 
	CREATE_CMD_REQ_BIN_LEN(C960_DisconnectDevice) 
	CREATE_CMD_REQ_BIN_LEN(C961_WriteNetworkKey) 
	CREATE_CMD_REQ_BIN_LEN(C962_WriteDeviceNicknameAddress) 
	CREATE_CMD_REQ_BIN_LEN(C963_WriteSession) 
	CREATE_CMD_REQ_BIN_LEN(C964_DeleteSession) 
	CREATE_CMD_REQ_BIN_LEN(C965_WriteSuperframe) 
	CREATE_CMD_REQ_BIN_LEN(C966_DeleteSuperframe) 
	CREATE_CMD_REQ_BIN_LEN(C967_WriteLink) 
	CREATE_CMD_REQ_BIN_LEN(C968_DeleteLink) 
	CREATE_CMD_REQ_BIN_LEN(C969_WriteGraphNeighbourPair) 
	CREATE_CMD_REQ_BIN_LEN(C970_DeleteGraphConnection) 
	CREATE_CMD_REQ_BIN_LEN(C971_WriteNeighbourPropertyFlag) 
	CREATE_CMD_REQ_BIN_LEN(C972_SuspendDevices) 
	CREATE_CMD_REQ_BIN_LEN(C973_WriteService) 
	CREATE_CMD_REQ_BIN_LEN(C974_WriteRoute) 
	CREATE_CMD_REQ_BIN_LEN(C975_DeleteRoute) 
	CREATE_CMD_REQ_BIN_LEN(C976_WriteSourceRoute) 
	CREATE_CMD_REQ_BIN_LEN(C977_DeleteSourceRoute) 
/////////////////////////////////////////4////////////////////////////////////////////////////
	CREATE_CMD_REQ_PARSED_LEN(C000_ReadUniqueIdentifier) 
	CREATE_CMD_REQ_PARSED_LEN(C001_ReadPrimaryVariable) 
	CREATE_CMD_REQ_PARSED_LEN(C002_ReadLoopCurrentAndPercentOfRange) 
	CREATE_CMD_REQ_PARSED_LEN(C003_ReadDynamicVariablesAndLoopCurrent) 
	CREATE_CMD_REQ_PARSED_LEN(C006_WritePollingAddress) 
	CREATE_CMD_REQ_PARSED_LEN(C007_ReadLoopConfiguration) 
	CREATE_CMD_REQ_PARSED_LEN(C008_ReadDynamicVariableClassifications) 
	CREATE_CMD_REQ_PARSED_LEN(C009_ReadDeviceVariablesWithStatus) 
	CREATE_CMD_REQ_PARSED_LEN(C011_ReadUniqueIdentifierAssociatedWithTag) 
	CREATE_CMD_REQ_PARSED_LEN(C012_ReadMessage) 
	CREATE_CMD_REQ_PARSED_LEN(C013_ReadTagDescriptorDate) 
	CREATE_CMD_REQ_PARSED_LEN(C014_ReadPrimaryVariableTransducerInformation) 
	CREATE_CMD_REQ_PARSED_LEN(C015_ReadDeviceInformation) 
	CREATE_CMD_REQ_PARSED_LEN(C016_ReadFinalAssemblyNumber) 
	CREATE_CMD_REQ_PARSED_LEN(C017_WriteMessage) 
	CREATE_CMD_REQ_PARSED_LEN(C018_WriteTagDescriptorDate) 
	CREATE_CMD_REQ_PARSED_LEN(C019_WriteFinalAssemblyNumber) 
	CREATE_CMD_REQ_PARSED_LEN(C020_ReadLongTag) 
	CREATE_CMD_REQ_PARSED_LEN(C021_ReadUniqueIdentifierAssociatedWithLongTag) 
	CREATE_CMD_REQ_PARSED_LEN(C022_WriteLongTag) 
	CREATE_CMD_REQ_PARSED_LEN(C033_ReadDeviceVariables) 
	CREATE_CMD_REQ_PARSED_LEN(C034_WritePrimaryVariableDampingValue) 
	CREATE_CMD_REQ_PARSED_LEN(C035_WritePrimaryVariableRangeValues) 
	CREATE_CMD_REQ_PARSED_LEN(C036_SetPrimaryVariableUpperRangeValue) 
	CREATE_CMD_REQ_PARSED_LEN(C037_SetPrimaryVariableLowerRangeValue) 
	CREATE_CMD_REQ_PARSED_LEN(C038_ResetConfigurationChangedFlag) 
	CREATE_CMD_REQ_PARSED_LEN(C040_EnterExitFixedCurrentMode) 
	CREATE_CMD_REQ_PARSED_LEN(C041_PerformSelfTest) 
	CREATE_CMD_REQ_PARSED_LEN(C042_PerformDeviceReset) 
	CREATE_CMD_REQ_PARSED_LEN(C043_SetPrimaryVariableZero) 
	CREATE_CMD_REQ_PARSED_LEN(C044_WritePrimaryVariableUnits) 
	CREATE_CMD_REQ_PARSED_LEN(C045_TrimLoopCurrentZero) 
	CREATE_CMD_REQ_PARSED_LEN(C046_TrimLoopCurrentGain) 
	CREATE_CMD_REQ_PARSED_LEN(C047_WritePrimaryVariableTransferFunction) 
	CREATE_CMD_REQ_PARSED_LEN(C048_ReadAdditionalDeviceStatus) 
	CREATE_CMD_REQ_PARSED_LEN(C049_WritePrimaryVariableTransducerSerialNumber) 
	CREATE_CMD_REQ_PARSED_LEN(C050_ReadDynamicVariableAssignments) 
	CREATE_CMD_REQ_PARSED_LEN(C051_WriteDynamicVariableAssignments) 
	CREATE_CMD_REQ_PARSED_LEN(C052_SetDeviceVariableZero) 
	CREATE_CMD_REQ_PARSED_LEN(C053_WriteDeviceVariableUnits) 
	CREATE_CMD_REQ_PARSED_LEN(C054_ReadDeviceVariableInformation) 
	CREATE_CMD_REQ_PARSED_LEN(C055_WriteDeviceVariableDampingValue) 
	CREATE_CMD_REQ_PARSED_LEN(C056_WriteDeviceVariableTransducerSerialNo) 
	CREATE_CMD_REQ_PARSED_LEN(C059_WriteNumberOfResponsePreambles) 
	CREATE_CMD_REQ_PARSED_LEN(C060_ReadAnalogChannelAndPercentOfRange) 
	CREATE_CMD_REQ_PARSED_LEN(C062_ReadAnalogChannels) 
	CREATE_CMD_REQ_PARSED_LEN(C063_ReadAnalogChannelInformation) 
	CREATE_CMD_REQ_PARSED_LEN(C064_WriteAnalogChannelAdditionalDampingValue) 
	CREATE_CMD_REQ_PARSED_LEN(C065_WriteAnalogChannelRangeValues) 
	CREATE_CMD_REQ_PARSED_LEN(C066_EnterExitFixedAnalogChannelMode) 
	CREATE_CMD_REQ_PARSED_LEN(C067_TrimAnalogChannelZero) 
	CREATE_CMD_REQ_PARSED_LEN(C068_TrimAnalogChannelGain) 
	CREATE_CMD_REQ_PARSED_LEN(C069_WriteAnalogChannelTransferFunction) 
	CREATE_CMD_REQ_PARSED_LEN(C070_ReadAnalogChannelEndpointValues) 
	CREATE_CMD_REQ_PARSED_LEN(C071_LockDevice) 
	CREATE_CMD_REQ_PARSED_LEN(C072_Squawk) 
	CREATE_CMD_REQ_PARSED_LEN(C073_FindDevice) 
	CREATE_CMD_REQ_PARSED_LEN(C074_ReadIOSystemCapabilities) 
	CREATE_CMD_REQ_PARSED_LEN(C075_PollSubDevice) 
	CREATE_CMD_REQ_PARSED_LEN(C076_ReadLockDeviceState) 
	CREATE_CMD_REQ_PARSED_LEN(C077_SendCommandToSubDevice) 
	CREATE_CMD_REQ_PARSED_LEN(C078_ReadAggregatedCommands) 
	CREATE_CMD_REQ_PARSED_LEN(C079_WriteDeviceVariable) 
	CREATE_CMD_REQ_PARSED_LEN(C080_ReadDeviceVariableTrimPoints) 
	CREATE_CMD_REQ_PARSED_LEN(C081_ReadDeviceVariableTrimGuidelines) 
	CREATE_CMD_REQ_PARSED_LEN(C082_WriteDeviceVariableTrimPoint) 
	CREATE_CMD_REQ_PARSED_LEN(C083_ResetDeviceVariableTrim) 
	CREATE_CMD_REQ_PARSED_LEN(C084_ReadSubDeviceIdentitySummary) 
	CREATE_CMD_REQ_PARSED_LEN(C085_ReadIOChannelStatistics) 
	CREATE_CMD_REQ_PARSED_LEN(C086_ReadSubDeviceStatistics) 
	CREATE_CMD_REQ_PARSED_LEN(C087_WriteIOSystemMasterMode) 
	CREATE_CMD_REQ_PARSED_LEN(C088_WriteIOSystemRetryCount) 
	CREATE_CMD_REQ_PARSED_LEN(C089_SetRealTimeClock) 
	CREATE_CMD_REQ_PARSED_LEN(C090_ReadRealTimeClock) 
	CREATE_CMD_REQ_PARSED_LEN(C091_ReadTrendConfiguration) 
	CREATE_CMD_REQ_PARSED_LEN(C092_WriteTrendConfiguration) 
	CREATE_CMD_REQ_PARSED_LEN(C093_ReadTrend) 
	CREATE_CMD_REQ_PARSED_LEN(C094_ReadIOSystemClientSideCommunicationStatistics) 
	CREATE_CMD_REQ_PARSED_LEN(C095_ReadDeviceCommunicationsStatistics) 
	CREATE_CMD_REQ_PARSED_LEN(C096_ReadSynchronousAction) 
	CREATE_CMD_REQ_PARSED_LEN(C097_ConfigureSynchronousAction) 
	CREATE_CMD_REQ_PARSED_LEN(C098_ReadCommandAction) 
	CREATE_CMD_REQ_PARSED_LEN(C099_ConfigureCommandAction) 
	CREATE_CMD_REQ_PARSED_LEN(C101_ReadSubDeviceToBurstMessageMap) 
	CREATE_CMD_REQ_PARSED_LEN(C102_MapSubDeviceToBurstMessage) 
	CREATE_CMD_REQ_PARSED_LEN(C103_WriteBurstPeriod) 
	CREATE_CMD_REQ_PARSED_LEN(C104_WriteBurstTrigger) 
	CREATE_CMD_REQ_PARSED_LEN(C105_ReadBurstModeConfiguration) 
	CREATE_CMD_REQ_PARSED_LEN(C106_FlushDelayedResponses) 
	CREATE_CMD_REQ_PARSED_LEN(C107_WriteBurstDeviceVariables) 
	CREATE_CMD_REQ_PARSED_LEN(C108_WriteBurstModeCommandNumber) 
	CREATE_CMD_REQ_PARSED_LEN(C109_BurstModeControl) 
	CREATE_CMD_REQ_PARSED_LEN(C113_CatchDeviceVariable) 
	CREATE_CMD_REQ_PARSED_LEN(C114_ReadCaughtDeviceVariable) 
	CREATE_CMD_REQ_PARSED_LEN(C115_ReadEventNotificationSummary) 
	CREATE_CMD_REQ_PARSED_LEN(C116_WriteEventNotificationBitMask) 
	CREATE_CMD_REQ_PARSED_LEN(C117_WriteEventNotificationTiming) 
	CREATE_CMD_REQ_PARSED_LEN(C118_EventNotificationControl) 
	CREATE_CMD_REQ_PARSED_LEN(C119_AcknowledgeEventNotification)
	CREATE_CMD_REQ_PARSED_LEN(C178_PublishedDynamicData)
	CREATE_CMD_REQ_PARSED_LEN(C512_ReadCountryCode) 
	//	CREATE_CMD_REQ_PARSED_LEN(C513_ReadCountryCode) 
	CREATE_CMD_REQ_PARSED_LEN(C768_WriteJoinKey) 
	CREATE_CMD_REQ_PARSED_LEN(C769_ReadJoinStatus) 
	CREATE_CMD_REQ_PARSED_LEN(C770_RequestActiveAdvertise) 
	CREATE_CMD_REQ_PARSED_LEN(C771_ForceJoin) 
	CREATE_CMD_REQ_PARSED_LEN(C772_ReadJoinModeConfiguration) 
	CREATE_CMD_REQ_PARSED_LEN(C773_WriteNetworkId) 
	CREATE_CMD_REQ_PARSED_LEN(C774_ReadNetworkId) 
	CREATE_CMD_REQ_PARSED_LEN(C777_ReadWirelessDeviceInformation) 
	CREATE_CMD_REQ_PARSED_LEN(C778_ReadBatteryLife) 
	CREATE_CMD_REQ_PARSED_LEN(C779_ReportDeviceHealth) 
	CREATE_CMD_REQ_PARSED_LEN(C780_ReportNeighborHealthList) 
	CREATE_CMD_REQ_PARSED_LEN(C781_ReadDeviceNicknameAddress) 
	CREATE_CMD_REQ_PARSED_LEN(C782_ReadSessionEntries) 
	CREATE_CMD_REQ_PARSED_LEN(C783_ReadSuperframeList) 
	CREATE_CMD_REQ_PARSED_LEN(C784_ReadLinkList) 
	CREATE_CMD_REQ_PARSED_LEN(C785_ReadGraphList) 
	CREATE_CMD_REQ_PARSED_LEN(C786_ReadNeighborPropertyFlag) 
	CREATE_CMD_REQ_PARSED_LEN(C787_ReportNeighborSignalLevels) 
	CREATE_CMD_REQ_PARSED_LEN(C788_AlarmPathDown) 
	CREATE_CMD_REQ_PARSED_LEN(C789_AlarmSourceRouteFailed) 
	CREATE_CMD_REQ_PARSED_LEN(C790_AlarmGraphRouteFailed) 
	CREATE_CMD_REQ_PARSED_LEN(C791_AlarmTransportLayerFailed) 
	CREATE_CMD_REQ_PARSED_LEN(C793_WriteUTCTime) 
	CREATE_CMD_REQ_PARSED_LEN(C794_ReadUTCTime) 
	CREATE_CMD_REQ_PARSED_LEN(C795_WriteTimerInterval) 
	CREATE_CMD_REQ_PARSED_LEN(C796_ReadTimerInterval) 
	CREATE_CMD_REQ_PARSED_LEN(C797_WriteRadioPower) 
	CREATE_CMD_REQ_PARSED_LEN(C798_ReadRadioPower) 
	CREATE_CMD_REQ_PARSED_LEN(C799_RequestService) 
	CREATE_CMD_REQ_PARSED_LEN(C800_ReadServiceList) 
	CREATE_CMD_REQ_PARSED_LEN(C801_DeleteService) 
	CREATE_CMD_REQ_PARSED_LEN(C802_ReadRouteList) 
	CREATE_CMD_REQ_PARSED_LEN(C803_ReadSourceRoute) 
	CREATE_CMD_REQ_PARSED_LEN(C804_ReadRadioCCAMode) 
	CREATE_CMD_REQ_PARSED_LEN(C805_WriteRadioCCAMode) 
	CREATE_CMD_REQ_PARSED_LEN(C806_ReadHandheldSuperframe) 
	CREATE_CMD_REQ_PARSED_LEN(C807_RequestHandheldSuperframeMode) 
	CREATE_CMD_REQ_PARSED_LEN(C808_ReadTimeToLive) 
	CREATE_CMD_REQ_PARSED_LEN(C809_WriteTimeToLive) 
	CREATE_CMD_REQ_PARSED_LEN(C810_ReadJoinPriority) 
	CREATE_CMD_REQ_PARSED_LEN(C811_WriteJoinPriority) 
	CREATE_CMD_REQ_PARSED_LEN(C812_ReadPacketReceivePriority) 
	CREATE_CMD_REQ_PARSED_LEN(C813_WritePacketReceivePriority) 
	CREATE_CMD_REQ_PARSED_LEN(C814_ReadDeviceListEntries) 
	CREATE_CMD_REQ_PARSED_LEN(C815_AddDeviceListTableEntry) 
	CREATE_CMD_REQ_PARSED_LEN(C816_DeleteDeviceListTableEntry) 
	CREATE_CMD_REQ_PARSED_LEN(C817_ReadChannelBlacklist) 
	CREATE_CMD_REQ_PARSED_LEN(C818_WriteChannelBlacklist) 
	CREATE_CMD_REQ_PARSED_LEN(C819_ReadBackOffExponent) 
	CREATE_CMD_REQ_PARSED_LEN(C820_WriteBackOffExponent) 
	CREATE_CMD_REQ_PARSED_LEN(C821_WriteNetworkAccessMode) 
	CREATE_CMD_REQ_PARSED_LEN(C822_ReadNetworkAccessMode) 
	CREATE_CMD_REQ_PARSED_LEN(C823_RequestSession) 
	CREATE_CMD_REQ_PARSED_LEN(C832_ReadNetworkDeviceIdentity) 
	CREATE_CMD_REQ_PARSED_LEN(C833_ReadNetworkDeviceNeighbourHealth) 
	CREATE_CMD_REQ_PARSED_LEN(C834_ReadNetworkTopologyInformation) 
	CREATE_CMD_REQ_PARSED_LEN(C835_ReadBurstMessageList) 
	CREATE_CMD_REQ_PARSED_LEN(C836_FlushCacheResponses) 
	CREATE_CMD_REQ_PARSED_LEN(C837_WriteUpdateNotificationBitMask) 
	CREATE_CMD_REQ_PARSED_LEN(C838_ReadUpdateNotificationBitMask) 
	CREATE_CMD_REQ_PARSED_LEN(C839_ChangeNotification) 
	CREATE_CMD_REQ_PARSED_LEN(C840_ReadDeviceStatistics) 
	CREATE_CMD_REQ_PARSED_LEN(C841_ReadNetworkDeviceIdentityByNickname) 
	CREATE_CMD_REQ_PARSED_LEN(C842_WriteDeviceSchedulingFlags) 
	CREATE_CMD_REQ_PARSED_LEN(C843_ReadDeviceSchedulingFlags) 
	CREATE_CMD_REQ_PARSED_LEN(C844_ReadNetworkConstraints) 
	CREATE_CMD_REQ_PARSED_LEN(C845_WriteNetworkConstraints) 
	CREATE_CMD_REQ_PARSED_LEN(C960_DisconnectDevice) 
	CREATE_CMD_REQ_PARSED_LEN(C961_WriteNetworkKey) 
	CREATE_CMD_REQ_PARSED_LEN(C962_WriteDeviceNicknameAddress) 
	CREATE_CMD_REQ_PARSED_LEN(C963_WriteSession) 
	CREATE_CMD_REQ_PARSED_LEN(C964_DeleteSession) 
	CREATE_CMD_REQ_PARSED_LEN(C965_WriteSuperframe) 
	CREATE_CMD_REQ_PARSED_LEN(C966_DeleteSuperframe) 
	CREATE_CMD_REQ_PARSED_LEN(C967_WriteLink) 
	CREATE_CMD_REQ_PARSED_LEN(C968_DeleteLink) 
	CREATE_CMD_REQ_PARSED_LEN(C969_WriteGraphNeighbourPair) 
	CREATE_CMD_REQ_PARSED_LEN(C970_DeleteGraphConnection) 
	CREATE_CMD_REQ_PARSED_LEN(C971_WriteNeighbourPropertyFlag) 
	CREATE_CMD_REQ_PARSED_LEN(C972_SuspendDevices) 
	CREATE_CMD_REQ_PARSED_LEN(C973_WriteService) 
	CREATE_CMD_REQ_PARSED_LEN(C974_WriteRoute) 
	CREATE_CMD_REQ_PARSED_LEN(C975_DeleteRoute) 
	CREATE_CMD_REQ_PARSED_LEN(C976_WriteSourceRoute) 
	CREATE_CMD_REQ_PARSED_LEN(C977_DeleteSourceRoute) 
//////////////////////////////////////////////////////////////////////////////////////////////




	const ParseExecuteComposerEntry g_parseReqComposeResp[] = {
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C000_ReadUniqueIdentifier),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C001_ReadPrimaryVariable),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C002_ReadLoopCurrentAndPercentOfRange),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C003_ReadDynamicVariablesAndLoopCurrent),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C006_WritePollingAddress),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C007_ReadLoopConfiguration),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C008_ReadDynamicVariableClassifications),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C009_ReadDeviceVariablesWithStatus),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C011_ReadUniqueIdentifierAssociatedWithTag),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C012_ReadMessage),
		//	CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C013_ReadTagDescriptorDate),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C014_ReadPrimaryVariableTransducerInformation),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C015_ReadDeviceInformation),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C016_ReadFinalAssemblyNumber),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C017_WriteMessage),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C018_WriteTagDescriptorDate),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C019_WriteFinalAssemblyNumber),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C020_ReadLongTag),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C021_ReadUniqueIdentifierAssociatedWithLongTag),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C022_WriteLongTag),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C033_ReadDeviceVariables),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C034_WritePrimaryVariableDampingValue),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C035_WritePrimaryVariableRangeValues),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C036_SetPrimaryVariableUpperRangeValue),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C037_SetPrimaryVariableLowerRangeValue),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C038_ResetConfigurationChangedFlag),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C040_EnterExitFixedCurrentMode),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C041_PerformSelfTest),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C042_PerformDeviceReset),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C043_SetPrimaryVariableZero),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C044_WritePrimaryVariableUnits),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C045_TrimLoopCurrentZero),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C046_TrimLoopCurrentGain),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C047_WritePrimaryVariableTransferFunction),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C048_ReadAdditionalDeviceStatus),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C049_WritePrimaryVariableTransducerSerialNumber),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C050_ReadDynamicVariableAssignments),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C051_WriteDynamicVariableAssignments),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C052_SetDeviceVariableZero),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C053_WriteDeviceVariableUnits),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C054_ReadDeviceVariableInformation),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C055_WriteDeviceVariableDampingValue),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C056_WriteDeviceVariableTransducerSerialNo),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C059_WriteNumberOfResponsePreambles),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C060_ReadAnalogChannelAndPercentOfRange),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C062_ReadAnalogChannels),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C063_ReadAnalogChannelInformation),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C064_WriteAnalogChannelAdditionalDampingValue),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C065_WriteAnalogChannelRangeValues),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C066_EnterExitFixedAnalogChannelMode),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C067_TrimAnalogChannelZero),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C068_TrimAnalogChannelGain),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C069_WriteAnalogChannelTransferFunction),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C070_ReadAnalogChannelEndpointValues),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C071_LockDevice),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C072_Squawk),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C073_FindDevice),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C074_ReadIOSystemCapabilities),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C075_PollSubDevice),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C076_ReadLockDeviceState),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C077_SendCommandToSubDevice),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C078_ReadAggregatedCommands),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C079_WriteDeviceVariable),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C080_ReadDeviceVariableTrimPoints),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C081_ReadDeviceVariableTrimGuidelines),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C082_WriteDeviceVariableTrimPoint),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C083_ResetDeviceVariableTrim),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C084_ReadSubDeviceIdentitySummary),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C085_ReadIOChannelStatistics),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C086_ReadSubDeviceStatistics),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C087_WriteIOSystemMasterMode),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C088_WriteIOSystemRetryCount),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C089_SetRealTimeClock),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C090_ReadRealTimeClock),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C091_ReadTrendConfiguration),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C092_WriteTrendConfiguration),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C093_ReadTrend),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C094_ReadIOSystemClientSideCommunicationStatistics),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C095_ReadDeviceCommunicationsStatistics),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C096_ReadSynchronousAction),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C097_ConfigureSynchronousAction),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C098_ReadCommandAction),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C099_ConfigureCommandAction),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C101_ReadSubDeviceToBurstMessageMap),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C102_MapSubDeviceToBurstMessage),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C103_WriteBurstPeriod),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C104_WriteBurstTrigger),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C105_ReadBurstModeConfiguration),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C106_FlushDelayedResponses),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C107_WriteBurstDeviceVariables),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C108_WriteBurstModeCommandNumber),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C109_BurstModeControl),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C113_CatchDeviceVariable),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C114_ReadCaughtDeviceVariable),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C115_ReadEventNotificationSummary),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C116_WriteEventNotificationBitMask),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C117_WriteEventNotificationTiming),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C118_EventNotificationControl),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C119_AcknowledgeEventNotification),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C178_PublishedDynamicData),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C512_ReadCountryCode),
		//	CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C513_ReadCountryCode),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C768_WriteJoinKey),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C769_ReadJoinStatus),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C770_RequestActiveAdvertise),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C771_ForceJoin),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C772_ReadJoinModeConfiguration),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C773_WriteNetworkId),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C774_ReadNetworkId),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C777_ReadWirelessDeviceInformation),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C778_ReadBatteryLife),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C779_ReportDeviceHealth),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C780_ReportNeighborHealthList),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C781_ReadDeviceNicknameAddress),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C782_ReadSessionEntries),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C783_ReadSuperframeList),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C784_ReadLinkList),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C785_ReadGraphList),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C786_ReadNeighborPropertyFlag),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C787_ReportNeighborSignalLevels),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C788_AlarmPathDown),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C789_AlarmSourceRouteFailed),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C790_AlarmGraphRouteFailed),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C791_AlarmTransportLayerFailed),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C793_WriteUTCTime),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C794_ReadUTCTime),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C795_WriteTimerInterval),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C796_ReadTimerInterval),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C797_WriteRadioPower),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C798_ReadRadioPower),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C799_RequestService),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C800_ReadServiceList),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C801_DeleteService),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C802_ReadRouteList),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C803_ReadSourceRoute),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C804_ReadRadioCCAMode),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C805_WriteRadioCCAMode),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C806_ReadHandheldSuperframe),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C807_RequestHandheldSuperframeMode),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C808_ReadTimeToLive),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C809_WriteTimeToLive),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C810_ReadJoinPriority),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C811_WriteJoinPriority),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C812_ReadPacketReceivePriority),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C813_WritePacketReceivePriority),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C814_ReadDeviceListEntries),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C815_AddDeviceListTableEntry),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C816_DeleteDeviceListTableEntry),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C817_ReadChannelBlacklist),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C818_WriteChannelBlacklist),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C819_ReadBackOffExponent),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C820_WriteBackOffExponent),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C821_WriteNetworkAccessMode),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C822_ReadNetworkAccessMode),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C823_RequestSession),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C832_ReadNetworkDeviceIdentity),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C833_ReadNetworkDeviceNeighbourHealth),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C834_ReadNetworkTopologyInformation),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C835_ReadBurstMessageList),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C836_FlushCacheResponses),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C837_WriteUpdateNotificationBitMask),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C838_ReadUpdateNotificationBitMask),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C839_ChangeNotification),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C840_ReadDeviceStatistics),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C841_ReadNetworkDeviceIdentityByNickname),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C842_WriteDeviceSchedulingFlags),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C843_ReadDeviceSchedulingFlags),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C844_ReadNetworkConstraints),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C845_WriteNetworkConstraints),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C960_DisconnectDevice),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C961_WriteNetworkKey),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C962_WriteDeviceNicknameAddress),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C963_WriteSession),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C964_DeleteSession),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C965_WriteSuperframe),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C966_DeleteSuperframe),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C967_WriteLink),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C968_DeleteLink),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C969_WriteGraphNeighbourPair),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C970_DeleteGraphConnection),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C971_WriteNeighbourPropertyFlag),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C972_SuspendDevices),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C973_WriteService),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C974_WriteRoute),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C975_DeleteRoute),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C976_WriteSourceRoute),
		CREATE_PARSER_REQ_COMPOSER_RESP_ENTRY(C977_DeleteSourceRoute),
		{0xffff, 0, 0} //nicu.dascalu - only for testing, to detect end of array
	};



	const ParseExecuteComposerEntry g_composeReqParseResp[] = {
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C000_ReadUniqueIdentifier),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C001_ReadPrimaryVariable),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C002_ReadLoopCurrentAndPercentOfRange),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C003_ReadDynamicVariablesAndLoopCurrent),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C006_WritePollingAddress),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C007_ReadLoopConfiguration),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C008_ReadDynamicVariableClassifications),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C009_ReadDeviceVariablesWithStatus),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C011_ReadUniqueIdentifierAssociatedWithTag),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C012_ReadMessage),
		//	CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C013_ReadTagDescriptorDate),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C014_ReadPrimaryVariableTransducerInformation),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C015_ReadDeviceInformation),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C016_ReadFinalAssemblyNumber),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C017_WriteMessage),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C018_WriteTagDescriptorDate),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C019_WriteFinalAssemblyNumber),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C020_ReadLongTag),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C021_ReadUniqueIdentifierAssociatedWithLongTag),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C022_WriteLongTag),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C033_ReadDeviceVariables),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C034_WritePrimaryVariableDampingValue),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C035_WritePrimaryVariableRangeValues),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C036_SetPrimaryVariableUpperRangeValue),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C037_SetPrimaryVariableLowerRangeValue),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C038_ResetConfigurationChangedFlag),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C040_EnterExitFixedCurrentMode),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C041_PerformSelfTest),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C042_PerformDeviceReset),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C043_SetPrimaryVariableZero),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C044_WritePrimaryVariableUnits),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C045_TrimLoopCurrentZero),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C046_TrimLoopCurrentGain),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C047_WritePrimaryVariableTransferFunction),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C048_ReadAdditionalDeviceStatus),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C049_WritePrimaryVariableTransducerSerialNumber),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C050_ReadDynamicVariableAssignments),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C051_WriteDynamicVariableAssignments),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C052_SetDeviceVariableZero),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C053_WriteDeviceVariableUnits),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C054_ReadDeviceVariableInformation),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C055_WriteDeviceVariableDampingValue),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C056_WriteDeviceVariableTransducerSerialNo),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C059_WriteNumberOfResponsePreambles),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C060_ReadAnalogChannelAndPercentOfRange),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C062_ReadAnalogChannels),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C063_ReadAnalogChannelInformation),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C064_WriteAnalogChannelAdditionalDampingValue),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C065_WriteAnalogChannelRangeValues),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C066_EnterExitFixedAnalogChannelMode),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C067_TrimAnalogChannelZero),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C068_TrimAnalogChannelGain),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C069_WriteAnalogChannelTransferFunction),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C070_ReadAnalogChannelEndpointValues),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C071_LockDevice),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C072_Squawk),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C073_FindDevice),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C074_ReadIOSystemCapabilities),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C075_PollSubDevice),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C076_ReadLockDeviceState),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C077_SendCommandToSubDevice),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C078_ReadAggregatedCommands),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C079_WriteDeviceVariable),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C080_ReadDeviceVariableTrimPoints),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C081_ReadDeviceVariableTrimGuidelines),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C082_WriteDeviceVariableTrimPoint),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C083_ResetDeviceVariableTrim),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C084_ReadSubDeviceIdentitySummary),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C085_ReadIOChannelStatistics),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C086_ReadSubDeviceStatistics),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C087_WriteIOSystemMasterMode),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C088_WriteIOSystemRetryCount),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C089_SetRealTimeClock),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C090_ReadRealTimeClock),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C091_ReadTrendConfiguration),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C092_WriteTrendConfiguration),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C093_ReadTrend),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C094_ReadIOSystemClientSideCommunicationStatistics),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C095_ReadDeviceCommunicationsStatistics),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C096_ReadSynchronousAction),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C097_ConfigureSynchronousAction),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C098_ReadCommandAction),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C099_ConfigureCommandAction),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C101_ReadSubDeviceToBurstMessageMap),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C102_MapSubDeviceToBurstMessage),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C103_WriteBurstPeriod),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C104_WriteBurstTrigger),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C105_ReadBurstModeConfiguration),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C106_FlushDelayedResponses),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C107_WriteBurstDeviceVariables),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C108_WriteBurstModeCommandNumber),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C109_BurstModeControl),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C113_CatchDeviceVariable),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C114_ReadCaughtDeviceVariable),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C115_ReadEventNotificationSummary),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C116_WriteEventNotificationBitMask),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C117_WriteEventNotificationTiming),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C118_EventNotificationControl),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C119_AcknowledgeEventNotification),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C178_PublishedDynamicData),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C512_ReadCountryCode),
		//	CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C513_ReadCountryCode),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C768_WriteJoinKey),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C769_ReadJoinStatus),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C770_RequestActiveAdvertise),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C771_ForceJoin),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C772_ReadJoinModeConfiguration),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C773_WriteNetworkId),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C774_ReadNetworkId),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C777_ReadWirelessDeviceInformation),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C778_ReadBatteryLife),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C779_ReportDeviceHealth),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C780_ReportNeighborHealthList),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C781_ReadDeviceNicknameAddress),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C782_ReadSessionEntries),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C783_ReadSuperframeList),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C784_ReadLinkList),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C785_ReadGraphList),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C786_ReadNeighborPropertyFlag),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C787_ReportNeighborSignalLevels),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C788_AlarmPathDown),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C789_AlarmSourceRouteFailed),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C790_AlarmGraphRouteFailed),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C791_AlarmTransportLayerFailed),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C793_WriteUTCTime),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C794_ReadUTCTime),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C795_WriteTimerInterval),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C796_ReadTimerInterval),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C797_WriteRadioPower),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C798_ReadRadioPower),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C799_RequestService),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C800_ReadServiceList),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C801_DeleteService),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C802_ReadRouteList),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C803_ReadSourceRoute),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C804_ReadRadioCCAMode),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C805_WriteRadioCCAMode),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C806_ReadHandheldSuperframe),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C807_RequestHandheldSuperframeMode),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C808_ReadTimeToLive),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C809_WriteTimeToLive),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C810_ReadJoinPriority),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C811_WriteJoinPriority),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C812_ReadPacketReceivePriority),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C813_WritePacketReceivePriority),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C814_ReadDeviceListEntries),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C815_AddDeviceListTableEntry),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C816_DeleteDeviceListTableEntry),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C817_ReadChannelBlacklist),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C818_WriteChannelBlacklist),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C819_ReadBackOffExponent),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C820_WriteBackOffExponent),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C821_WriteNetworkAccessMode),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C822_ReadNetworkAccessMode),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C823_RequestSession),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C832_ReadNetworkDeviceIdentity),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C833_ReadNetworkDeviceNeighbourHealth),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C834_ReadNetworkTopologyInformation),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C835_ReadBurstMessageList),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C836_FlushCacheResponses),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C837_WriteUpdateNotificationBitMask),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C838_ReadUpdateNotificationBitMask),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C839_ChangeNotification),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C840_ReadDeviceStatistics),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C841_ReadNetworkDeviceIdentityByNickname),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C842_WriteDeviceSchedulingFlags),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C843_ReadDeviceSchedulingFlags),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C844_ReadNetworkConstraints),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C845_WriteNetworkConstraints),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C960_DisconnectDevice),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C961_WriteNetworkKey),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C962_WriteDeviceNicknameAddress),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C963_WriteSession),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C964_DeleteSession),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C965_WriteSuperframe),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C966_DeleteSuperframe),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C967_WriteLink),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C968_DeleteLink),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C969_WriteGraphNeighbourPair),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C970_DeleteGraphConnection),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C971_WriteNeighbourPropertyFlag),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C972_SuspendDevices),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C973_WriteService),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C974_WriteRoute),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C975_DeleteRoute),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C976_WriteSourceRoute),
		CREATE_COMPOSER_REQ_PARSER_RESP_ENTRY(C977_DeleteSourceRoute),
		{0xffff, 0, 0} //nicu.dascalu - only for testing, to detect end of array
	};


int const g_nComposeReqParseRespSize = sizeof(g_composeReqParseResp)/sizeof(ParseExecuteComposerEntry);
int const g_nParseReqComposeRespSize = sizeof(g_parseReqComposeResp)/sizeof(ParseExecuteComposerEntry);

} // namespace gateway
} // namespace hart7 
